name: Deploy LampV2 CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2 
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8   
          
      - name: Receive Github Tag
        id: tag
        run: echo "::set-output name=TAG_NUMBER::$(git branch)"

      - name: Bump version code
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{github.run_number}}
          versionName: ${{steps.tag.outputs.TAG_NUMBER}}
 
      - name: Grant rights
        run: chmod +x build.gradle
          
      - name: Build with Gradle
        id: build
        run: ./gradlew build
        
      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease
        
        
          
    

 
